name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  PYTHON_LATEST: "3.10"

jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Dependencies"
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements/test.txt
          pip install tox-gh-actions

      - run: "tox"

  package:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_LATEST}}

      - name: Install Dependencies
        run: pip install build twine check-wheel-contents

      - run: python -m build --sdist --wheel .

      - run: ls -l dist

      - run: check-wheel-contents dist/*.whl

      - run: python -m twine check dist/*


  install-dev:
    name: Verify dev env
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_LATEST}}

      - run: pip install -r requirements/dev.txt

      - run: pip list

      - run: python -c "import conformity_migration"
